# Site Info
title:              "Chenyue's Blog"
description:        "Chenyue Cai's periodic contemplation on arts, science and life"
author_name:        "Chenyue Cai" # change this to your name
logo_url:           https://avatars.githubusercontent.com/u/43433308?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://github.com/ChenyueCai/blog # main url
baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
